language: python

sudo: false

#env:
#    - TOX_ENV=py39-django317
#    - TOX_ENV=py38-django317
#    - TOX_ENV=py37-django317
#    - TOX_ENV=py36-django317
#    - TOX_ENV=py39-django221
#    - TOX_ENV=py38-django221
#    - TOX_ENV=py37-django221
#    - TOX_ENV=py36-django221
#    - TOX_ENV=py39-django211
#    - TOX_ENV=py38-django211
#    - TOX_ENV=py37-django211
#    - TOX_ENV=py36-django211
#    - TOX_ENV=py39-djangomaster
#    - TOX_ENV=py38-djangomaster
#    - TOX_ENV=py37-djangomaster
#    - TOX_ENV=py36-djangomaster
#    - TOX_ENV=coverage_combine
#    - TOX_ENV=docs

matrix:
  include:
  - python: "3.6"
    env: TOX_ENV=py36-django211
    dist: xenial
  - python: "3.7"
    env: TOX_ENV=py37-django221
    dist: xenial
  - python: "3.7"
    env: TOX_ENV=py37-django317
    dist: xenial
  - python: "3.7"
    env: TOX_ENV=py37-djangomaster
    dist: xenial
  - python: "3.8"
    env: TOX_ENV=py38-django221
    dist: xenial
  - python: "3.8"
    env: TOX_ENV=py38-django317
    dist: xenial
  - python: "3.8"
    env: TOX_ENV=py38-djangomaster
    dist: xenial
  - python: "3.9"
    env: TOX_ENV=py39-django221
    dist: xenial
  - python: "3.9"
    env: TOX_ENV=py39-django317
    dist: xenial
  - python: "3.9"
    env: TOX_ENV=py39-djangomaster
    dist: xenial
#  - python: "3.7"
#    env: TOX_ENV=flake8
#  - python: "3.6"
#    env: TOX_ENV=gettext
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=coverage_combine
    - env: TOX_ENV=docs
    - env: TOX_ENV=py39-djangomaster
    - env: TOX_ENV=py38-djangomaster
    - env: TOX_ENV=py37-djangomaster

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email:
        - alainivars@gmail.com
